### ISSUE TITLE
Object has been destroyed

### ISSUE THREAD

**Issue by linonetwo** [reZach/i18next-electron-fs-backend#1]
After closing window, and click the tray icon to recreate window, I get following error:

```
Uncaught Exception:
Error: Object has been destroyed
    at BrowserWindow.<anonymous> (/xxx/node_modules/i18next-electron-fs-backend/lib/index.js:1:2234)
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
```

In https://github.com/reZach/secure-electron-template

**Comment by reZach** [comment]
Thanks for reporting this, @linonetwo. Do you have more of a stack trace, and what OS was this on?

**Comment by reZach** [comment]
@linonetwo Doing some research on this issue, namely [stack overflow](https://stackoverflow.com/questions/38309240/object-has-been-destroyed-when-open-secondary-child-window-in-electron-js) and the [electron docs](https://github.com/electron/electron/blob/v1.2.6/docs/api/browser-window.md#event-closed), it seems it is this line causing the error.

```javascript
// Emitted when the window is closed.
win.on("closed", () => {
  // Dereference the window object, usually you would store windows
  // in an array if your app supports multi windows, this is the time
  // when you should delete the corresponding element.
  win = null;
});
```

Upon closing the window, the reference should be closed. This is intended behavior as closing the window should shut down the app. If you'd like to not shut down the app, you may try this code. I do not know how you could ever close the app completely down if you coded it up like this, though.

```javascript
win.on("closed", (event) => {
  event.preventDefault();
});
```

I am going to close this issue here, as it's an issue/question related to [`secure-electron-template`](https://github.com/reZach/secure-electron-template) rather than this repository. If you'd like to continue the conversation I suggest we take it to secure-electron-template. (You may link this issue so we keep good history).

Thanks!

**Comment by linonetwo** [comment]
I think maybe you should check `event.sender.isDestroyed()` when using `ipcMain`, and check `win.isDestroyed()` before using `win`?

**Comment by linonetwo** [comment]
I copy the prettified code, and found error is from this line:

https://github.com/reZach/i18next-electron-fs-backend/blob/1c4aed8a1f22b90c6f470a440c46708e4e2273ed/src/index.js#L48

**Comment by reZach** [comment]
@linonetwo Thank you for your investigation. I found that `mainBindings()` is creating listeners and not clearing them properly. This is why we get the object destroyed error, the listener is calling a method on the old (closed/destroyed BrowserWindow). I've upgraded the package to `1.1.2` which you should get this version for the fix.

In addition to version `1.1.2`, you'll want to add this piece of code in the **window-all-closed** event.
```javascript
// Quit when all windows are closed.
app.on("window-all-closed", () => {
  // On macOS it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
  if (process.platform !== "darwin") {
    app.quit();
  } else {
    i18nextBackend.clearMainBindings(ipcMain); // added!
  }
});
```

**Comment by linonetwo** [comment]
I confirm it is fixed for good, thank you for your great works!
