### ISSUE TITLE
{Question} best way to translate menu items ?

### ISSUE THREAD

**Issue by fragoulin** [reZach/i18next-electron-fs-backend#3]
As I understand, translations are available from the renderer process.
In order to translate stuff in the main process, how should we proceed to keep a secure and maintainable code ?

I was thinking of duplicating the i18n config slightly modified to work with the main process (using i18next-node-fs-backend for example), but maybe there's a better way.

What should be the recommended way to translate menu items ?

**Comment by reZach** [comment]
Thanks @fragoulin for your interest in this idea. 

This was something I too was considering when building out the [`secure-electron-template`](https://github.com/reZach/secure-electron-template) repository. I had trouble so I left everything in English.

I _think_ the problem with **i18next-electron-fs-backend** is that it makes use of **window** in the backend, which obviously fails when loading from the main process because there _is_ no **window** object. I've [started](https://github.com/reZach/i18next-electron-fs-backend/commit/1af4d358a260873b92b1af084dc15668660736f4) on a branch for this work, but haven't gotten it figured out completely. 

To make this work securely, I suggest we first need to get the backend to work _without_ the **window** object, and then load the backend [like we are in menu.js](https://github.com/reZach/secure-electron-template/blob/master/app/electron/menu.js). I then think we need to [call .t](https://www.i18next.com/overview/comparison-to-others#i-18-next-is-complicated) from the backend object to pass in keys to return translated menu components. This is my general idea of how to proceed.

I'd be open if you made some progress or submitted a PR with the complete work if you are willing to help with this 😄 . Is this something you'd like to make a PR for?

**Comment by fragoulin** [comment]
Currently I have a simple solution with a i18next-node-fs-backend configuration for the main process.
It works well, and I guess it's secure, but I'm not satisfied with this solution of having two configurations for i18next.

I'd be glad to look at your branch, and eventually submit a PR if I manage to reach a satisfying solution.

**Comment by reZach** [comment]
@fragoulin can you please share your solution how you integrated this? The new commit does not work with my template library, I'm curious how it works with yours.

**Comment by fragoulin** [comment]
There is a problem with require fs. It is executed despite the if statement.
So I added a try/catch. Check commit https://github.com/fragoulin/i18next-electron-fs-backend/commit/2b1e780c1443c090e7533ca366b523ddc82718de
However this solution is not ideal because it will display a warning in the console. I don't have this issue with my project because I use ES6 import statements. There's surely a good solution using CommonJS, but I don't have one in mind.

For the template, check my fork here : https://github.com/fragoulin/secure-electron-template with commit https://github.com/fragoulin/secure-electron-template/commit/2b6a17a2a1fd3af2dd36c68d72ce4b4f4fbc066c to log translation of hello in the main process console.

**Comment by reZach** [comment]
Hi @fragoulin , thanks for trying to help resolve this. I do see `fs` continue to be required, although all require calls fail. Like you, I do not know why it is doing that.

The call to the backend to translate doesn't actually work, `.t("Hello")` works in the sense that because the key is in the translation file, but only because of that. If you change the key to something that doesn't exist in the translation file, `this.fs` is attempted to be called and fails.

Is your other template similar? 
It's completely up to you, but can you explain how I might be able to use ES6 instead of CommonJS? I will attempt to head down this route in order to get my template up and working.

**Comment by fragoulin** [comment]
Conditional requires should work with CommonJS. This is also maybe related to webpack configuration, which will parse all JS files and require the JS out of the box. Unfortunately I'm far from being a webpack expert to try to debug that.

You're right there's a bug in the app at this line : https://github.com/reZach/i18next-electron-fs-backend/blob/master/src/index.js#L271
You have to use this.fs instead of fs.

My template is different because I use electron-forge and typescript. But the security configuration is the same, so the difference is not related our templates. The problem is related to something between webpack configuration and the code. I'm not even sure using ES6 will solve the problem.

I published my repo : https://github.com/fragoulin/cellar-door
Feel free to check the configuration.

**Comment by reZach** [comment]
@fragoulin thanks for trying to work through this, but is it possible if you take the unminified/minified source from the commit that works from this repository?

I do want your project to succeed, but I feel frustrated because I can't figure this out and on my list of things I want to code, this is lower on that list and I don't like leaving a commit on this repo that's not compatible with secure-electron-template. I want to revert this change from my master branch for this reason.

Let me know what you think.

**Comment by fragoulin** [comment]
In order to get rid of this change to keep a clean master branch, you could simply make another branch specific for this update.

**Comment by reZach** [comment]
@fragoulin I rolled back your changes. I left the master branch in a bad state, and the PRs were split across multiple commits. I put some of your changes back in master, but not all since I'm short on time. Just an FYI.

**Comment by reZach** [comment]
@fragoulin I'm going to think using i18next-fs-backend (which is a replacement for i18next-node-fs-backend) is going to be the way to go. If we have to use 2 i18n config files, I think that would be best. After thinking about it, requesting translation files via ipc in the main process doesn't make any sense and have since begun trying to [get this to work](https://github.com/reZach/secure-electron-template/tree/broken-menu-translation). I've [opened a bug](https://github.com/i18next/i18next-fs-backend/issues/17) since I'm currently stuck.

**Comment by reZach** [comment]
@fragoulin , please follow the guidance [here](https://github.com/reZach/secure-electron-template/commit/ae8eb1fa7931be0c700cf66a37ed6dd6072964f9) if you'd like to set up translations for menu options. I assume this is with secure-electron-template? The changes should be mostly compatible with the version you have/were working with.

**Comment by Ciberusps** [comment]
> @fragoulin , please follow the guidance [here](https://github.com/reZach/secure-electron-template/commit/ae8eb1fa7931be0c700cf66a37ed6dd6072964f9) if you'd like to set up translations for menu options. I assume this is with secure-electron-template? The changes should be mostly compatible with the version you have/were working with.

Awesome can you add info that `t` also available in main process to readme, its important that there is a way to localalize not only frontend

**Comment by reZach** [comment]
@Ciberusps 

Is there any particular place you would find this information (use `i18next-fs-backend` for main process and `i18next-electron-fs-backend` for renderer) to be helpful in order that if others have the same question, the answer can be found easily?
