### ISSUE TITLE
Using saveMissing and saveMissingTo doesn't work

### ISSUE THREAD

**Issue by egll-tech** [reZach/i18next-electron-fs-backend#8]
I am trying to save any missing key, but not sure what is wrong.
```
// i18n.ts
import i18n from "i18next";
import backend from "i18next-electron-fs-backend";
import { initReactI18next } from "react-i18next";

i18n
  .use(backend)
  .use(initReactI18next)
  .init({
    backend: {
      loadPath: "assets/translations/{{lng}}/{{ns}}.json",
      addPath: "assets/translations/{{lng}}/{{ns}}.missing.json",
      ipcRenderer: window.api.i18nextElectronBackend,
      debug: true,
    },
    supportedLngs: ["en", "es"],
    fallbackLng: false,
    ns: ["common"],
    react: {
      useSuspense: false,
    },
    saveMissing: true,
    saveMissingTo: "current",
    lng: window.api.locale,
    debug: true,
  });

export default i18n;
```

**Comment by reZach** [comment]
All of your settings @egll-tech are the ones that I know of that are required to generate missing keys, namely

`saveMissing: true`
`saveMissingTo: "current"`
`lng: window.api.locale`
`fallbackLng: false`

I would try hard-coding values for `lng` instead of using the value from `window` and see if that makes a difference.

**Comment by reZach** [comment]
@egll-tech Please re-open if you are still experiencing an issue after my latest comment.
